CREATE SEQUENCE orders_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE orders (
    id             BIGINT       PRIMARY KEY,
    customer_email VARCHAR(255) NOT NULL,
    status         VARCHAR(32)  NOT NULL,
    placed_on      DATE         NOT NULL,
    total_cents    BIGINT       NOT NULL
);

CREATE TABLE order_lines (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT      NOT NULL REFERENCES orders (id),
    sku              VARCHAR(64) NOT NULL,
    quantity         INT         NOT NULL,
    unit_price_cents BIGINT      NOT NULL
);
