CREATE TABLE shipments (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT      NOT NULL REFERENCES orders (id),
    shipped_on      DATE        NOT NULL,
    carrier         VARCHAR(64) NOT NULL,
    tracking_number VARCHAR(64) NOT NULL
);

CREATE TABLE shipment_lines (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT      NOT NULL REFERENCES shipments (id),
    sku         VARCHAR(64) NOT NULL,
    quantity    INT         NOT NULL
);
